### ISSUE TITLE
Rustdoc fails to build after https://github.com/rust-lang/rust/pull/43482

### ISSUE THREAD

**Issue by o01eg** [gentoo/gentoo-rust#277]
After merge https://github.com/rust-lang/rust/pull/43482 `rustdoc` in `dev-lanf/rust-9999` fails to buld:
```
    Finished release [optimized] target(s) in 70.1 secs
      < ToolBuild { compiler: Compiler { stage: 1, host: "x86_64-unknown-linux-gnu" }, target: "x86_64-unknown-linux-gnu", tool: "rustdoc", mode: Librustc }
      c Sysroot { compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-gnu" } }
    < Rustdoc { target_compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-gnu" } }
running: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc" "--html-after-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/footer.inc" "--html-before-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/version_info.html" "--html-in-header" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/favicon.inc" "--markdown-playground-url" "https://play.rust-lang.org/" "-o" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/book" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/book/index.md" "--markdown-css" "rust.css"
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc: error while loading shared libraries: librustc_driver-e46c20968ab39e5f.so: cannot open shared object file: No such file or directory


command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc" "--html-after-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/footer.inc" "--html-before-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/version_info.html" "--html-in-header" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/favicon.inc" "--markdown-playground-url" "https://play.rust-lang.org/" "-o" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/book" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/book/index.md" "--markdown-css" "rust.css"
expected success, got: exit code: 127


Traceback (most recent call last):
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 816, in <module>
    main()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 799, in main
    bootstrap()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 790, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/bootstrap dist -v
make: *** [Makefile:70: dist] Error 1
```

Required library exists:
```
# find /tmp/portage/ -iname librustc_driver-e46c20968ab39e5f.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-e46c20968ab39e5f.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e46c20968ab39e5f.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-e46c20968ab39e5f.so
```

**Comment by o01eg** [comment]
I rewrite ebuild to use `x.py` but got same error:

```
       Fresh rustdoc-tool v0.0.0 (file:///tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/tools/rustdoc)
    Finished release [optimized] target(s) in 0.0 secs
        < ToolBuild { compiler: Compiler { stage: 1, host: "x86_64-unknown-linux-gnu" }, target: "x86_64-unknown-linux-gnu", tool: "rustdoc", mode: Librustc }
        c Sysroot { compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-gnu" } }
      < Rustdoc { target_compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-gnu" } }
running: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc" "--html-after-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/footer.inc" "--html-before-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/version_info.html" "--html-in-header" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/favicon.inc" "--markdown-playground-url" "https://play.rust-lang.org/" "-o" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/book" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/book/index.md" "--markdown-css" "rust.css"
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc: error while loading shared libraries: librustc_driver-f242960f86c74636.so: cannot open shared object file: No such file or directory


command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc" "--html-after-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/footer.inc" "--html-before-content" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/version_info.html" "--html-in-header" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/favicon.inc" "--markdown-playground-url" "https://play.rust-lang.org/" "-o" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/doc/book" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/doc/book/index.md" "--markdown-css" "rust.css"
expected success, got: exit code: 127


Traceback (most recent call last):
  File "x.py", line 20, in <module>
    bootstrap.main()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 799, in main
    bootstrap()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 790, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/bootstrap install
```

**Comment by o01eg** [comment]
It looks like caused by https://github.com/rust-lang/rust/issues/43289
