### ISSUE TITLE
rust-1.26.0 doesn't compile (multilib issue?)

### ISSUE THREAD

**Issue by Feandil** [gentoo/gentoo-rust#337]
Hi,

There seems to be an issue with the rust-1.26.0 ebuild, which introduces mutlilib support:
```
running: /var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/build/bootstrap/debug/bootstrap build --verbose --config=/var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/config.toml -j3
finding compilers
CC_x86_64-unknown-linux-gnu = "x86_64-pc-linux-gnu-gcc -m64"
AR_x86_64-unknown-linux-gnu = "x86_64-pc-linux-gnu-ar"
CXX_x86_64-unknown-linux-gnu = "x86_64-pc-linux-gnu-g++ -m64"
running sanity check
thread 'main' panicked at '

couldn't find required command: "x86_64-pc-linux-gnu-gcc -m64"

', bootstrap/sanity.rs:66:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/src/bootstrap/bootstrap.py", line 800, in main
    bootstrap(help_triggered)
  File "/var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/src/bootstrap/bootstrap.py", line 791, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/build/bootstrap/debug/bootstrap build --verbose --config=/var/tmp/portage/dev-lang/rust-1.26.0/work/rustc-1.26.0-src/config.toml -j3
```

Please note what command it's trying to find: ```"x86_64-pc-linux-gnu-gcc -m64"```
Compared to 1.25.0, this is adding a cflag (```-m64```) to the cc variable: is that supported by rust? (It doesn't seem to parse and split on the space...)

I can give more information on my setup if needed

**Comment by gibix** [comment]
This is caused by how rust [makes some sanity checks](https://github.com/rust-lang/rust/blob/94516c5038b1203988a3be1d7912d08a6db86202/src/bootstrap/sanity.rs#L46) on executables in the configuraition. I'll look at this.
